# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of your application
COPY . .

# Expose the port that your Node.js app will use
EXPOSE 3000

# Start the Node.js service
CMD ["node", "get-dealership.js"]
